name: Daily Commit

on:
  schedule:
    # Runs every day at 04:30 UTC (you can choose a specific time)
    - cron: '30 4 * * *'
  workflow_dispatch:  # Allows manual trigger (optional but useful for testing)

permissions:
  contents: write # This grants write access to the repository contents

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Update file with email 22f1001034@ds.study.iitm.ac.in
        run: |
          echo "Last run at $(date -u)" > last-run.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add last-run.txt
          git commit -m "Daily commit from GitHub Actions"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main

